### ISSUE TITLE
Under Maintenance Response from API Gateway

### ISSUE THREAD

**Issue by kespinola** [holaplex/helm-charts#111]
## Goal
Holaplex engineers should be able to configure the api gateway to return a service unavailable while under scheduled maintenance.

**Comment by mpwsh** [comment]
added a variable to the hub-gateway helm chart to enable/disable `maintenanceMode`.   PR https://github.com/holaplex/helm-charts/pull/113

```yaml
maintenanceMode:
  enabled: true
```

Setting the value to true will trigger the addition of `response-rewrite` and `mocking` plugins on `hub` subdomain routes, and just `mocking` on the `api` routes.

 - response-rewrite -- Adds a base64 string with the Maintenance HTML page
 - mocking -- Stops the request so it doesn't reach the upstream service. 

Response when hitting 'hub.holaplex.com/*'


![Image](https://github.com/holaplex/helm-charts/assets/13471075/eafa1a24-517b-418e-8b05-a1c25b818ea2)



mocking can also be used to add a static response, which we use to respond with JSON if someone hits the API endpoint 



![Image](https://github.com/holaplex/helm-charts/assets/13471075/c7302591-117d-48a9-81b0-8e243251da48)
