### ISSUE TITLE
Friendly API Auth Errors

### ISSUE THREAD

**Issue by kespinola** [holaplex/helm-charts#129]
I get this error when I input a project id that is not in my auth token's organization. I'd rather see something like "access denied"

![Image](https://user-images.githubusercontent.com/24394839/256618794-bd3a552b-8a64-468b-8832-3d568cede6c6.png)

**Comment by mpwsh** [comment]
PR https://github.com/holaplex/helm-charts/pull/130

**Comment by kespinola** [comment]
done.
